
FROM nginx:alpine

# Kopiere Frontend-Dateien
COPY frontend/ /usr/share/nginx/html

# Kopiere Nginx-Konfiguration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Setze Rechte
RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
